<% if %w(development test).include?(Rails.env) %>
<%= IO.read('config/database.local.yml') %>
<% end %>

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
