default: &default
  adapter: postgresql
  encoding: utf8
  host: 'localhost'
  username: 'user'
  password: 'password'

development:
  <<: *default
  database: 'katana_dev'

test:
  <<: *default
  database: 'katana_test'
